#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -gt 1 ]; then
  echo "用法: sudo $0 [RDK直连IP]" >&2
  exit 2
fi
if [ "$(id -u)" -ne 0 ]; then
  echo "需要root权限写入Chrony配置，请使用sudo。" >&2
  exit 1
fi
if ! command -v chronyd >/dev/null 2>&1 || ! command -v chronyc >/dev/null 2>&1; then
  echo "未安装chrony，请先在NX安装chrony软件包。" >&2
  exit 1
fi

RDK_ADDRESS="${1:-10.43.0.20}"
if [[ ! "$RDK_ADDRESS" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  echo "RDK直连IP格式无效: $RDK_ADDRESS" >&2
  exit 2
fi

CONF_DIR="/etc/chrony/conf.d"
CONF_FILE="$CONF_DIR/robocon-rdk-client.conf"
install -d -m 0755 "$CONF_DIR"
TEMP_FILE="$(mktemp)"
trap 'rm -f "$TEMP_FILE"' EXIT
cat > "$TEMP_FILE" <<EOF
# Robot NX-RDK direct-link clock client. Generated by stereo_3d_pipeline.
server ${RDK_ADDRESS} iburst xleave prefer minpoll -4 maxpoll -4
makestep 0.1 3
rtcsync
EOF
install -m 0644 "$TEMP_FILE" "$CONF_FILE"
systemctl restart chrony
chronyc waitsync 30 0.002
chronyc tracking
chronyc sources -v
echo "NX Chrony客户端已配置，RDK时间源: $RDK_ADDRESS"
