"""NX realtime algorithm matrix case definitions."""

from __future__ import annotations

from dataclasses import dataclass, field


MODE_KEYS = {
    "bbox_pair",
    "bbox_edges",
    "circle_center",
    "circle_edges",
    "roi_edge_centroid",
    "roi_radial_center",
    "roi_edge_pair_center",
    "roi_corner_points",
    "roi_texture_points",
    "roi_binary_points",
    "roi_orb_points",
    "roi_brisk_points",
    "roi_akaze_points",
    "roi_sift_points",
    "roi_iou_region_color_patch",
    "roi_patch_iou_color_edge",
    "roi_cuda_template_match",
    "roi_cuda_stereo_bm",
    "roi_cuda_stereo_sgm",
    "roi_center_patch",
    "roi_subpixel",
    "epipolar_fallback",
    "fallback_template",
    "fallback_feature_points",
}


@dataclass
class Case:
    name: str
    modes: dict[str, bool] = field(default_factory=dict)
    candidate_fields: tuple[str, ...] = ()
    support_field: str | None = None
    subpixel_enabled: bool | None = None
    yaml_scalars: dict[str, str] = field(default_factory=dict)
    neural_backend: str | None = None
    neural_engine: str | None = None
    roi_size: int = 224
    top_k: int = 128
    descriptor_dim: int = 64
    neural_min_matches: int = 8
    neural_max_y_error_px: float = 2.0
    neural_max_disp_delta_px: float = 32.0
    neural_final_disp_gate_px: float = 2.0
    neural_min_score: float = 0.0
    note: str = ""


CASES = (
    Case(
        "bbox_pair",
        {"bbox_pair": True},
        ("z_bbox_center",),
        note="YOLO bbox-center disparity only; no ROI keypoints",
    ),
    Case(
        "circle_center",
        {"circle_center": True},
        ("z_circle_center",),
        note="circle-fit center disparity only",
    ),
    Case(
        "roi_edge_centroid",
        {"roi_edge_centroid": True},
        ("z_roi_edge_centroid",),
        note="CUDA ROI edge centroid only",
    ),
    Case(
        "roi_radial_center",
        {"roi_radial_center": True},
        ("z_roi_radial_center",),
        note="CUDA radial center only",
    ),
    Case(
        "roi_edge_pair_center",
        {"roi_edge_pair_center": True},
        ("z_roi_edge_pair_center",),
        note="CUDA paired-edge center only",
    ),
    Case(
        "roi_center_patch",
        {"roi_center_patch": True},
        ("z_roi_center_patch",),
        support_field="subpixel_support",
        note="CUDA center-patch ZNCC only",
    ),
    Case(
        "roi_subpixel",
        {"roi_subpixel": True},
        ("z_roi_multi_point",),
        support_field="subpixel_support",
        subpixel_enabled=True,
        note="CUDA multi-point subpixel only",
    ),
    Case(
        "opencv_cuda_orb",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        note="true OpenCV CUDA ORB + CUDA matcher",
    ),
    Case(
        "opencv_cpu_brisk",
        {"roi_brisk_points": True},
        ("z_roi_brisk_points",),
        support_field="roi_brisk_points_support",
        note="true OpenCV CPU BRISK",
    ),
    Case(
        "opencv_cpu_akaze",
        {"roi_akaze_points": True},
        ("z_roi_akaze_points",),
        support_field="roi_akaze_points_support",
        note="true OpenCV CPU AKAZE",
    ),
    Case(
        "opencv_cpu_sift",
        {"roi_sift_points": True},
        ("z_roi_sift_points",),
        support_field="roi_sift_points_support",
        note="true OpenCV CPU SIFT",
    ),
    Case(
        "iou_region_color_patch",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        note="CUDA BGR color IoU/patch candidate",
    ),
    Case(
        "patch_iou_color_edge",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        note="CUDA BGR color-edge patch candidate",
    ),
    Case(
        "opencv_cuda_template_match",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        note="OpenCV CUDA TemplateMatching small-ROI epipolar candidate",
    ),
    Case(
        "opencv_cuda_stereo_bm",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        note="OpenCV CUDA StereoBM small-ROI dense disparity candidate",
    ),
    Case(
        "opencv_cuda_stereo_sgm",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        note="OpenCV CUDA StereoSGM small-ROI dense disparity candidate",
    ),
    Case(
        "neural_xfeat",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=64,
        descriptor_dim=64,
        note="TensorRT XFeat 128 extractor; C++ postprocess/mutual-NN",
    ),
    Case(
        "neural_aliked",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="aliked",
        neural_engine="aliked_extractor_224_top128.engine",
        descriptor_dim=128,
    ),
    Case(
        "neural_superpoint_lightglue",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_224_top128.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=256,
        note="TensorRT SuperPoint extractor; direct descriptor matching fallback",
    ),
)
APPROX_CASES = (
    Case(
        "approx_corner_points",
        {"roi_corner_points": True},
        ("z_roi_corner_points",),
        support_field="roi_corner_points_support",
        note="custom CUDA sparse-lite corner; not OpenCV ORB/BRISK/AKAZE/SIFT",
    ),
    Case(
        "approx_texture_points",
        {"roi_texture_points": True},
        ("z_roi_texture_points",),
        support_field="roi_texture_points_support",
        note="custom CUDA sparse-lite texture; diagnostic only",
    ),
    Case(
        "approx_binary_points",
        {"roi_binary_points": True},
        ("z_roi_binary_points",),
        support_field="roi_binary_points_support",
        note="custom CUDA sparse-lite binary; diagnostic only",
    ),
)


ORB_FAST_SWEEP = {
    "subpixel_patch_radius": "3",
    "subpixel_search_radius_px": "4",
    "subpixel_max_points": "8",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.08",
    "subpixel_max_disp_delta_px": "6.0",
    "subpixel_max_stddev_px": "2.5",
    "feature_y_tolerance_px": "3.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.70",
    "feature_mad_scale": "3.5",
    "feature_ransac_gate_px": "2.0",
}

ORB_WIDE_Y_SWEEP = {
    "subpixel_patch_radius": "5",
    "subpixel_search_radius_px": "8",
    "subpixel_max_points": "12",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.08",
    "subpixel_max_disp_delta_px": "10.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "8.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.90",
    "feature_mad_scale": "4.0",
    "feature_ransac_gate_px": "3.0",
    "feature_sphere_radius_scale": "2.8",
}

COLOR_OFFLINE_TUNED = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "12",
    "subpixel_min_points": "4",
    "subpixel_min_confidence": "0.54",
    "subpixel_max_disp_delta_px": "6.0",
    "subpixel_max_stddev_px": "1.5",
    "feature_y_tolerance_px": "1.0",
    "feature_reverse_check_px": "1.0",
    "feature_overlap_scale": "0.55",
    "feature_mad_scale": "2.5",
    "feature_ransac_gate_px": "0.75",
}

COLOR_WIDE_SEARCH = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "24",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.25",
    "subpixel_max_disp_delta_px": "18.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "4.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.85",
    "feature_mad_scale": "4.0",
    "feature_ransac_gate_px": "3.0",
    "feature_sphere_radius_scale": "2.5",
}

TEMPLATE_PATCH9_SWEEP = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "16",
    "subpixel_min_confidence": "0.35",
    "subpixel_max_disp_delta_px": "10.0",
    "feature_y_tolerance_px": "2.0",
    "feature_overlap_scale": "0.70",
    "feature_sphere_radius_scale": "2.2",
}

DENSE_PATCH9_SWEEP = {
    "subpixel_patch_radius": "9",
    "subpixel_min_points": "4",
    "subpixel_min_confidence": "0.12",
    "subpixel_max_disp_delta_px": "18.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "3.0",
    "feature_overlap_scale": "0.80",
    "feature_sphere_radius_scale": "2.5",
}


RELAXED_CASES = (
    Case(
        "realtime_gpu_bundle",
        {
            "bbox_pair": True,
            "circle_center": True,
            "roi_edge_centroid": True,
            "roi_radial_center": True,
            "roi_edge_pair_center": True,
            "roi_center_patch": True,
            "roi_subpixel": True,
        },
        (
            "z_bbox_center",
            "z_circle_center",
            "z_roi_edge_centroid",
            "z_roi_radial_center",
            "z_roi_edge_pair_center",
            "z_roi_center_patch",
            "z_roi_multi_point",
        ),
        support_field="subpixel_support",
        subpixel_enabled=True,
        note="diagnostic only: all 100fps-capable CUDA depth candidates enabled together",
    ),
    Case(
        "opencv_cuda_orb_relaxed",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: true OpenCV CUDA ORB with relaxed gates",
    ),
    Case(
        "opencv_cuda_orb_fast48",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_FAST_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB, smaller ROI/search and 48-point cap",
    ),
    Case(
        "opencv_cuda_orb_wide_y",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_WIDE_Y_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB with wide y/overlap gates",
    ),
    Case(
        "iou_region_color_patch_relaxed",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: CUDA color IoU/patch with relaxed gates",
    ),
    Case(
        "iou_region_color_patch_offline_tuned",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color IoU/patch with offline best patch/y settings",
    ),
    Case(
        "iou_region_color_patch_wide_search",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color IoU/patch with wider search and looser gates",
    ),
    Case(
        "patch_iou_color_edge_relaxed",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: CUDA color-edge patch with relaxed gates",
    ),
    Case(
        "patch_iou_color_edge_offline_tuned",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color-edge patch with offline best patch/y settings",
    ),
    Case(
        "patch_iou_color_edge_wide_search",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color-edge patch with wider search and looser gates",
    ),
    Case(
        "opencv_cuda_template_match_relaxed",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars={
            "subpixel_patch_radius": "7",
            "subpixel_search_radius_px": "16",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA TemplateMatching with wider search/gates",
    ),
    Case(
        "opencv_cuda_template_match_patch9",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars=TEMPLATE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA TemplateMatching patch radius 9",
    ),
    Case(
        "opencv_cuda_stereo_bm_relaxed",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoBM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_bm_patch9",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoBM larger census/block window",
    ),
    Case(
        "opencv_cuda_stereo_sgm_relaxed",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoSGM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_sgm_patch9",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoSGM larger aggregation window",
    ),
    Case(
        "neural_xfeat_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT XFeat with relaxed gates",
    ),
    Case(
        "neural_xfeat_96_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_96.engine",
        roi_size=96,
        top_k=32,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 96 extractor top32",
    ),
    Case(
        "neural_xfeat_96_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_96.engine",
        roi_size=96,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 96 extractor top64",
    ),
    Case(
        "neural_xfeat_128_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=32,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 128 extractor top32",
    ),
    Case(
        "neural_xfeat_128_top96",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=96,
        descriptor_dim=64,
        note="P2 sweep: TensorRT XFeat 128 extractor top96",
    ),
    Case(
        "neural_xfeat_160",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_160.engine",
        roi_size=160,
        top_k=96,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 160 extractor",
    ),
    Case(
        "neural_xfeat_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_160.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 160 extractor top64",
    ),
    Case(
        "neural_xfeat_224",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor",
    ),
    Case(
        "neural_xfeat_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor top64",
    ),
    Case(
        "neural_xfeat_224_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=32,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor top32",
    ),
    Case(
        "neural_xfeat_224_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=64,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT XFeat 224 extractor with relaxed gates",
    ),
    Case(
        "neural_superpoint_lightglue_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_224_top128.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=256,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT SuperPoint extractor with relaxed gates",
    ),
    Case(
        "neural_superpoint_128_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_128_top64.engine",
        roi_size=128,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 128/top64",
    ),
    Case(
        "neural_superpoint_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_160_top64.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 160/top64",
    ),
    Case(
        "neural_superpoint_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_224_top64.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 224/top64",
    ),
    Case(
        "neural_aliked_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="aliked",
        neural_engine="aliked_extractor_160_top64.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=128,
        neural_min_matches=4,
        note="P2 sweep: ALIKED fixed extractor if a TensorRT engine is available",
    ),
    Case(
        "neural_aliked_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="aliked",
        neural_engine="aliked_extractor_224_top64.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=128,
        neural_min_matches=4,
        note="P2 sweep: ALIKED fixed extractor 224/top64 if engine exists",
    ),
)
