"""Relaxed and P2 sweep NX algorithm matrix cases."""

from __future__ import annotations

from nx_algorithm_case_types import Case


ORB_FAST_SWEEP = {
    "subpixel_patch_radius": "3",
    "subpixel_search_radius_px": "4",
    "subpixel_max_points": "8",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.08",
    "subpixel_max_disp_delta_px": "6.0",
    "subpixel_max_stddev_px": "2.5",
    "feature_y_tolerance_px": "3.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.70",
    "feature_mad_scale": "3.5",
    "feature_ransac_gate_px": "2.0",
}

ORB_WIDE_Y_SWEEP = {
    "subpixel_patch_radius": "5",
    "subpixel_search_radius_px": "8",
    "subpixel_max_points": "12",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.08",
    "subpixel_max_disp_delta_px": "10.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "8.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.90",
    "feature_mad_scale": "4.0",
    "feature_ransac_gate_px": "3.0",
    "feature_sphere_radius_scale": "2.8",
}

COLOR_OFFLINE_TUNED = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "12",
    "subpixel_min_points": "4",
    "subpixel_min_confidence": "0.54",
    "subpixel_max_disp_delta_px": "6.0",
    "subpixel_max_stddev_px": "1.5",
    "feature_y_tolerance_px": "1.0",
    "feature_reverse_check_px": "1.0",
    "feature_overlap_scale": "0.55",
    "feature_mad_scale": "2.5",
    "feature_ransac_gate_px": "0.75",
}

COLOR_WIDE_SEARCH = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "24",
    "subpixel_min_points": "3",
    "subpixel_min_confidence": "0.25",
    "subpixel_max_disp_delta_px": "18.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "4.0",
    "feature_reverse_check_px": "-1.0",
    "feature_overlap_scale": "0.85",
    "feature_mad_scale": "4.0",
    "feature_ransac_gate_px": "3.0",
    "feature_sphere_radius_scale": "2.5",
}

TEMPLATE_PATCH9_SWEEP = {
    "subpixel_patch_radius": "9",
    "subpixel_search_radius_px": "16",
    "subpixel_min_confidence": "0.35",
    "subpixel_max_disp_delta_px": "10.0",
    "feature_y_tolerance_px": "2.0",
    "feature_overlap_scale": "0.70",
    "feature_sphere_radius_scale": "2.2",
}

DENSE_PATCH9_SWEEP = {
    "subpixel_patch_radius": "9",
    "subpixel_min_points": "4",
    "subpixel_min_confidence": "0.12",
    "subpixel_max_disp_delta_px": "18.0",
    "subpixel_max_stddev_px": "3.0",
    "feature_y_tolerance_px": "3.0",
    "feature_overlap_scale": "0.80",
    "feature_sphere_radius_scale": "2.5",
}


RELAXED_CASES = (
    Case(
        "realtime_gpu_bundle",
        {
            "bbox_pair": True,
            "circle_center": True,
            "roi_edge_centroid": True,
            "roi_radial_center": True,
            "roi_edge_pair_center": True,
            "roi_center_patch": True,
            "roi_subpixel": True,
        },
        (
            "z_bbox_center",
            "z_circle_center",
            "z_roi_edge_centroid",
            "z_roi_radial_center",
            "z_roi_edge_pair_center",
            "z_roi_center_patch",
            "z_roi_multi_point",
        ),
        support_field="subpixel_support",
        subpixel_enabled=True,
        note="diagnostic only: all 100fps-capable CUDA depth candidates enabled together",
    ),
    Case(
        "opencv_cuda_orb_relaxed",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: true OpenCV CUDA ORB with relaxed gates",
    ),
    Case(
        "opencv_cuda_orb_fast48",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_FAST_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB, smaller ROI/search and 48-point cap",
    ),
    Case(
        "opencv_cuda_orb_wide_y",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_WIDE_Y_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB with wide y/overlap gates",
    ),
    Case(
        "iou_region_color_patch_relaxed",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: CUDA color IoU/patch with relaxed gates",
    ),
    Case(
        "iou_region_color_patch_offline_tuned",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color IoU/patch with offline best patch/y settings",
    ),
    Case(
        "iou_region_color_patch_wide_search",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color IoU/patch with wider search and looser gates",
    ),
    Case(
        "patch_iou_color_edge_relaxed",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "8.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "6.0",
            "feature_reverse_check_px": "-1.0",
            "feature_overlap_scale": "0.90",
            "feature_mad_scale": "4.0",
            "feature_ransac_gate_px": "3.0",
        },
        note="diagnostic only: CUDA color-edge patch with relaxed gates",
    ),
    Case(
        "patch_iou_color_edge_offline_tuned",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color-edge patch with offline best patch/y settings",
    ),
    Case(
        "patch_iou_color_edge_wide_search",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color-edge patch with wider search and looser gates",
    ),
    Case(
        "opencv_cuda_template_match_relaxed",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars={
            "subpixel_patch_radius": "7",
            "subpixel_search_radius_px": "16",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA TemplateMatching with wider search/gates",
    ),
    Case(
        "opencv_cuda_template_match_patch9",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars=TEMPLATE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA TemplateMatching patch radius 9",
    ),
    Case(
        "opencv_cuda_stereo_bm_relaxed",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoBM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_bm_patch9",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoBM larger census/block window",
    ),
    Case(
        "opencv_cuda_stereo_sgm_relaxed",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoSGM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_sgm_patch9",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoSGM larger aggregation window",
    ),
    Case(
        "neural_xfeat_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT XFeat with relaxed gates",
    ),
    Case(
        "neural_xfeat_96_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_96.engine",
        roi_size=96,
        top_k=32,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 96 extractor top32",
    ),
    Case(
        "neural_xfeat_96_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_96.engine",
        roi_size=96,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 96 extractor top64",
    ),
    Case(
        "neural_xfeat_128_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=32,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 128 extractor top32",
    ),
    Case(
        "neural_xfeat_128_top96",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_128.engine",
        roi_size=128,
        top_k=96,
        descriptor_dim=64,
        note="P2 sweep: TensorRT XFeat 128 extractor top96",
    ),
    Case(
        "neural_xfeat_160",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_160.engine",
        roi_size=160,
        top_k=96,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 160 extractor",
    ),
    Case(
        "neural_xfeat_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_160.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=64,
        neural_min_matches=4,
        note="P2 sweep: TensorRT XFeat 160 extractor top64",
    ),
    Case(
        "neural_xfeat_224",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor",
    ),
    Case(
        "neural_xfeat_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor top64",
    ),
    Case(
        "neural_xfeat_224_top32",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=32,
        descriptor_dim=64,
        note="diagnostic only: TensorRT XFeat 224 extractor top32",
    ),
    Case(
        "neural_xfeat_224_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="xfeat",
        neural_engine="xfeat_extractor_224.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=64,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT XFeat 224 extractor with relaxed gates",
    ),
    Case(
        "neural_superpoint_lightglue_relaxed",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_224_top128.engine",
        roi_size=224,
        top_k=128,
        descriptor_dim=256,
        neural_min_matches=4,
        neural_max_y_error_px=6.0,
        neural_max_disp_delta_px=96.0,
        neural_final_disp_gate_px=6.0,
        note="diagnostic only: TensorRT SuperPoint extractor with relaxed gates",
    ),
    Case(
        "neural_superpoint_128_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_128_top64.engine",
        roi_size=128,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 128/top64",
    ),
    Case(
        "neural_superpoint_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_160_top64.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 160/top64",
    ),
    Case(
        "neural_superpoint_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="superpoint_lightglue",
        neural_engine="superpoint_extractor_224_top64.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=256,
        neural_min_matches=4,
        note="P2 sweep: TensorRT SuperPoint fixed extractor 224/top64",
    ),
    Case(
        "neural_aliked_160_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="aliked",
        neural_engine="aliked_extractor_160_top64.engine",
        roi_size=160,
        top_k=64,
        descriptor_dim=128,
        neural_min_matches=4,
        note="P2 sweep: ALIKED fixed extractor if a TensorRT engine is available",
    ),
    Case(
        "neural_aliked_224_top64",
        candidate_fields=("z_roi_neural_feature",),
        support_field="roi_neural_feature_support",
        neural_backend="aliked",
        neural_engine="aliked_extractor_224_top64.engine",
        roi_size=224,
        top_k=64,
        descriptor_dim=128,
        neural_min_matches=4,
        note="P2 sweep: ALIKED fixed extractor 224/top64 if engine exists",
    ),
)
