"""CUDA and OpenCV CUDA P2 NX algorithm sweep cases."""

from __future__ import annotations

from nx_algorithm_case_sweep_scalars import (
    COLOR_OFFLINE_TUNED,
    COLOR_WIDE_SEARCH,
    DENSE_PATCH9_SWEEP,
    ORB_FAST_SWEEP,
    ORB_WIDE_Y_SWEEP,
    RELAXED_FEATURE_GATES,
    TEMPLATE_PATCH9_SWEEP,
)
from nx_algorithm_case_types import Case


CUDA_P2_CASES = (
    Case(
        "realtime_gpu_bundle",
        {
            "bbox_pair": True,
            "circle_center": True,
            "roi_edge_centroid": True,
            "roi_radial_center": True,
            "roi_edge_pair_center": True,
            "roi_center_patch": True,
            "roi_subpixel": True,
        },
        (
            "z_bbox_center",
            "z_circle_center",
            "z_roi_edge_centroid",
            "z_roi_radial_center",
            "z_roi_edge_pair_center",
            "z_roi_center_patch",
            "z_roi_multi_point",
        ),
        support_field="subpixel_support",
        subpixel_enabled=True,
        note="diagnostic only: all 100fps-capable CUDA depth candidates enabled together",
    ),
    Case(
        "opencv_cuda_orb_relaxed",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=RELAXED_FEATURE_GATES,
        note="diagnostic only: true OpenCV CUDA ORB with relaxed gates",
    ),
    Case(
        "opencv_cuda_orb_fast48",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_FAST_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB, smaller ROI/search and 48-point cap",
    ),
    Case(
        "opencv_cuda_orb_wide_y",
        {"roi_orb_points": True},
        ("z_roi_orb_points",),
        support_field="roi_orb_points_support",
        yaml_scalars=ORB_WIDE_Y_SWEEP,
        note="P2 sweep: true OpenCV CUDA ORB with wide y/overlap gates",
    ),
    Case(
        "iou_region_color_patch_relaxed",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=RELAXED_FEATURE_GATES,
        note="diagnostic only: CUDA color IoU/patch with relaxed gates",
    ),
    Case(
        "iou_region_color_patch_offline_tuned",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color IoU/patch with offline best patch/y settings",
    ),
    Case(
        "iou_region_color_patch_wide_search",
        {"roi_iou_region_color_patch": True},
        ("z_roi_iou_region_color_patch",),
        support_field="roi_iou_region_color_patch_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color IoU/patch with wider search and looser gates",
    ),
    Case(
        "patch_iou_color_edge_relaxed",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=RELAXED_FEATURE_GATES,
        note="diagnostic only: CUDA color-edge patch with relaxed gates",
    ),
    Case(
        "patch_iou_color_edge_offline_tuned",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_OFFLINE_TUNED,
        note="P2 sweep: CUDA color-edge patch with offline best patch/y settings",
    ),
    Case(
        "patch_iou_color_edge_wide_search",
        {"roi_patch_iou_color_edge": True},
        ("z_roi_patch_iou_color_edge",),
        support_field="roi_patch_iou_color_edge_support",
        yaml_scalars=COLOR_WIDE_SEARCH,
        note="P2 sweep: CUDA color-edge patch with wider search and looser gates",
    ),
    Case(
        "opencv_cuda_template_match_relaxed",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars={
            "subpixel_patch_radius": "7",
            "subpixel_search_radius_px": "16",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA TemplateMatching with wider search/gates",
    ),
    Case(
        "opencv_cuda_template_match_patch9",
        {"roi_cuda_template_match": True},
        ("z_roi_cuda_template_match",),
        support_field="roi_cuda_template_match_support",
        yaml_scalars=TEMPLATE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA TemplateMatching patch radius 9",
    ),
    Case(
        "opencv_cuda_stereo_bm_relaxed",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoBM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_bm_patch9",
        {"roi_cuda_stereo_bm": True},
        ("z_roi_cuda_stereo_bm",),
        support_field="roi_cuda_stereo_bm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoBM larger census/block window",
    ),
    Case(
        "opencv_cuda_stereo_sgm_relaxed",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars={
            "subpixel_min_points": "3",
            "subpixel_min_confidence": "0.10",
            "subpixel_max_disp_delta_px": "16.0",
            "subpixel_max_stddev_px": "3.0",
            "feature_y_tolerance_px": "4.0",
            "feature_overlap_scale": "0.85",
            "feature_sphere_radius_scale": "2.5",
        },
        note="diagnostic only: OpenCV CUDA StereoSGM with relaxed gates",
    ),
    Case(
        "opencv_cuda_stereo_sgm_patch9",
        {"roi_cuda_stereo_sgm": True},
        ("z_roi_cuda_stereo_sgm",),
        support_field="roi_cuda_stereo_sgm_support",
        yaml_scalars=DENSE_PATCH9_SWEEP,
        note="P2 sweep: OpenCV CUDA StereoSGM larger aggregation window",
    ),
)
